spring:
  datasource:
    name: supermarketdb
    url: jdbc:h2:mem:tempsupermarketdb
  jpa:
    show-sql: true

#H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console

#Feign client config
product:
  service:
    value: supermarket
    url: http://localhost:8081
