spring:
  datasource:
    name: supermarketdb
  jpa:
    show-sql: true

#H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console

#Feign client settings
product:
  service:
    value: supermarket-test
    url: http://localhost:8081
